### PR TITLE
Parse tracing

### LINKED ISSUE #35: Feature request: Add tracing support, for debugging purposes
It would be cool to add support for outputting parsing information as the input stream is context. This functionality would have been very useful at the start when I was implementing the initial Kerberos specification

As an example - a library that does this is https://github.com/dmendel/bindata which is a declarative library for parsing binary structure which has a tracing feature:

```ruby
require 'bindata'

class Polygon < BinData::Record
  endian :little
  uint8 :num_points, :value => lambda { points.length }
  array :points, :initial_length => :num_points do
    double :x
    double :y
  end
end

data =
  "\x03\x00\x00\x00\x00\x00\x00\xf0\x3f\x00\x00\x00\x00\x00\x00\x00" \
  "\x40\x00\x00\x00\x00\x00\x00\x08\x40\x00\x00\x00\x00\x00\x00\x10" \
  "\x40\x00\x00\x00\x00\x00\x00\x14\x40\x00\x00\x00\x00\x00\x00\x18" \
  "\x40".b

BinData::trace_reading($stdout) do
  puts Polygon.read(data)
end
```

Outputs:
```
obj.num_points => 3
obj.points[0].x => 1.0
obj.points[0].y => 2.0
obj.points[1].x => 3.0
obj.points[1].y => 4.0
obj.points[2].x => 5.0
obj.points[2].y => 6.0
{:num_points=>3, :points=>[{:x=>1.0, :y=>2.0}, {:x=>3.0, :y=>4.0}, {:x=>5.0, :y=>6.0}]}
```

The API could be similar for RASN1, and it would be useful for users that are parsing complex structures. At the minute a parsing failure results in a crash, and I manually delete fields until I get things to parse again successfully

### PR DESCRIPTION
**Pull request by sdaubert**
Fix #35

### CODE REVIEW

**Comment by adfoster-r7** [comment]
Awesome! I tried this with some of the Kerberos models it worked for me with crashing:

```
Ticket EXPLICIT SEQUENCE id: 1 (0x61), len: 268 (0x82010c), data: 0x30820108a003020105a10c1b0a4445...
SEQUENCE id: 16 (0x30), len: 264 (0x820108), data: 0xa003020105a10c1b0a44454d4f2e4c...
tkt_vno EXPLICIT INTEGER id: 0 (0xa0), len: 3 (0x03), data: 0x020105
tkt_vno INTEGER id: 2 (0x02), len: 1 (0x01), data: 0x05
realm EXPLICIT KerberosString id: 1 (0xa1), len: 12 (0x0c), data: 0x1b0a44454d4f2e4c4f43414c
KerberosString id: 27 (0x1b), len: 10 (0x0a), data: 0x44454d4f2e4c4f43414c
IMPLICIT  id: 2 (0xa2), len: 31 (0x1f), data: 0x301da003020101a11630141b066b72...
PrincipalName SEQUENCE id: 16 (0x30), len: 29 (0x1d), data: 0xa003020101a11630141b066b726274...
name_type EXPLICIT INT32 id: 0 (0xa0), len: 3 (0x03), data: 0x020101
name_type INT32 id: 2 (0x02), len: 1 (0x01), data: 0x01
name_string EXPLICIT SEQUENCE OF id: 1 (0xa1), len: 22 (0x16), data: 0x30141b066b72627467741b0a44454d...
SEQUENCE OF id: 16 (0x30), len: 20 (0x14), data: 0x1b066b72627467741b0a44454d4f2e...
KerberosString id: 27 (0x1b), len: 6 (0x06), data: 0x6b7262746774
KerberosString id: 27 (0x1b), len: 10 (0x0a), data: 0x44454d4f2e4c4f43414c
IMPLICIT  id: 3 (0xa3), len: 209 (0x81d1), data: 0x3081cea003020117a103020102a281...
EncryptedData SEQUENCE id: 16 (0x30), len: 206 (0x81ce), data: 0xa003020117a103020102a281c10481...
etype EXPLICIT INT32 id: 0 (0xa0), len: 3 (0x03), data: 0x020117
etype INT32 id: 2 (0x02), len: 1 (0x01), data: 0x17
kvno EXPLICIT OPTIONAL UINT32 id: 1 (0xa1), len: 3 (0x03), data: 0x020102
kvno UINT32 id: 2 (0x02), len: 1 (0x01), data: 0x02
cipher EXPLICIT OCTET STRING id: 2 (0xa2), len: 193 (0x81c1), data: 0x0481be55e745c36fa22847ab9c8613...
OCTET STRING id: 4 (0x04), len: 190 (0x81be), data: 0x55e745c36fa22847ab9c8613eb1da8...
```

The output is a bit hard to understand for me though with more complex models. I wonder if it would be possible to indent the output? Potentially in a similar way to the inspection logic?

```
=> (Ticket) Ticket APPLICATION [1] EXPLICIT SEQUENCE:
  tkt_vno CONTEXT [0] EXPLICIT INTEGER: 5
  realm CONTEXT [1] EXPLICIT KerberosString: "DEMO.LOCAL"
  CONTEXT [2] IMPLICIT :    (PrincipalName) PrincipalName SEQUENCE:
    name_type CONTEXT [0] EXPLICIT INT32: 1
    name_string CONTEXT [1] EXPLICIT SEQUENCE OF:
      KerberosString: "krbtgt"
      KerberosString: "DEMO.LOCAL"


  CONTEXT [3] IMPLICIT :    (EncryptedData) EncryptedData SEQUENCE:
    etype CONTEXT [0] EXPLICIT INT32: 23
    kvno CONTEXT [1] EXPLICIT UINT32: 2 OPTIONAL
    cipher CONTEXT [2] EXPLICIT OCTET STRING: "U\xE7E\xC3o\xA2(G\xAB\x9C\x86\x13\xEB\x1D\xA8\x98\xECg\x1C\x1F\x15Fk\xE0J\xF2M=\xF7\xE41zO\x15/`\xDD\x98\xA8\xE1\x97ko\xC1$Fl\xA9\x1E\xE26'\xE3\xFA\x99\f\x9Bw\f\xE2X\x02h\xC4T*,]lK\xC8\xBC\x04\x8F\nD'x\xDCK>\x01\xBE\xAC\xF7\x8EzP\xC6>w\xD9e$\xD5\x1A\x18\xA1\x84q\x85\x98/T\x8BV\xE3\xFB,\xE20\x84\x06UU\xEA1\x8B\x84\x00\xE3\x1A\xC3\xA8\xC2\xAC\xC0x?Ght\xCCb\xA6\xCF\xF4k\xAE\xAF'\xDE\x1AM\xB7\xA8\x9Fvzy*B\x12{\xD2\xBE\xC9\x98|D8@\xBDI\xCD>\xDCe\xC7\x8BD\xF5\xA5\xD4f\x0E\xFDX\x9D19'\xD7\xFC\x81\a\xA3*\x1C<"
```

I'm not sure what the perfect output is just yet for the more complex models when it comes to readability/debuggability - but just as an extra data point openssl's parser has similar support that might give inspiration:

```
$ openssl asn1parse -inform DER -in ./result.bin -i -dump
    0:d=0  hl=4 l= 268 cons: appl [ 1 ]        
    4:d=1  hl=4 l= 264 cons:  SEQUENCE          
    8:d=2  hl=2 l=   3 cons:   cont [ 0 ]        
   10:d=3  hl=2 l=   1 prim:    INTEGER           :05
   13:d=2  hl=2 l=  12 cons:   cont [ 1 ]        
   15:d=3  hl=2 l=  10 prim:    GENERALSTRING     
      0000 - 44 45 4d 4f 2e 4c 4f 43-41 4c                     DEMO.LOCAL
   27:d=2  hl=2 l=  31 cons:   cont [ 2 ]        
   29:d=3  hl=2 l=  29 cons:    SEQUENCE          
   31:d=4  hl=2 l=   3 cons:     cont [ 0 ]        
   33:d=5  hl=2 l=   1 prim:      INTEGER           :01
   36:d=4  hl=2 l=  22 cons:     cont [ 1 ]        
   38:d=5  hl=2 l=  20 cons:      SEQUENCE          
   40:d=6  hl=2 l=   6 prim:       GENERALSTRING     
      0000 - 6b 72 62 74 67 74                                 krbtgt
   48:d=6  hl=2 l=  10 prim:       GENERALSTRING     
      0000 - 44 45 4d 4f 2e 4c 4f 43-41 4c                     DEMO.LOCAL
   60:d=2  hl=3 l= 209 cons:   cont [ 3 ]        
   63:d=3  hl=3 l= 206 cons:    SEQUENCE          
   66:d=4  hl=2 l=   3 cons:     cont [ 0 ]        
   68:d=5  hl=2 l=   1 prim:      INTEGER           :17
   71:d=4  hl=2 l=   3 cons:     cont [ 1 ]        
   73:d=5  hl=2 l=   1 prim:      INTEGER           :02
   76:d=4  hl=3 l= 193 cons:     cont [ 2 ]        
   79:d=5  hl=3 l= 190 prim:      OCTET STRING      
      0000 - 55 e7 45 c3 6f a2 28 47-ab 9c 86 13 eb 1d a8 98   U.E.o.(G........
      0010 - ec 67 1c 1f 15 46 6b e0-4a f2 4d 3d f7 e4 31 7a   .g...Fk.J.M=..1z
      0020 - 4f 15 2f 60 dd 98 a8 e1-97 6b 6f c1 24 46 6c a9   O./`.....ko.$Fl.
      0030 - 1e e2 36 27 e3 fa 99 0c-9b 77 0c e2 58 02 68 c4   ..6'.....w..X.h.
      0040 - 54 2a 2c 5d 6c 4b c8 bc-04 8f 0a 44 27 78 dc 4b   T*,]lK.....D'x.K
      0050 - 3e 01 be ac f7 8e 7a 50-c6 3e 77 d9 65 24 d5 1a   >.....zP.>w.e$..
      0060 - 18 a1 84 71 85 98 2f 54-8b 56 e3 fb 2c e2 30 84   ...q../T.V..,.0.
      0070 - 06 55 55 ea 31 8b 84 00-e3 1a c3 a8 c2 ac c0 78   .UU.1..........x
      0080 - 3f 47 68 74 cc 62 a6 cf-f4 6b ae af 27 de 1a 4d   ?Ght.b...k..'..M
      0090 - b7 a8 9f 76 7a 79 2a 42-12 7b d2 be c9 98 7c 44   ...vzy*B.{....|D
      00a0 - 38 40 bd 49 cd 3e dc 65-c7 8b 44 f5 a5 d4 66 0e   8@.I.>.e..D...f.
      00b0 - fd 58 9d 31 39 27 d7 fc-81 07 a3 2a 1c 3c         .X.19'.....*.<
```

**Comment by adfoster-r7** [comment]
This is really nice! 🎉 

I was wondering your thoughts on moving the sequence number to the start of the line - as it helps visually group the numbers

```diff
-  KrbError EXPLICIT SEQUENCE id: 30 (0x7e), len: 141 (0x818d)
+  [30] KrbError EXPLICIT SEQUENCE id: 30 (0x7e), len: 141 (0x818d)
  SEQUENCE id: 16 (0x30), len: 138 (0x818a)
-    pvno EXPLICIT INTEGER id: 0 (0xa0), len: 3 (0x03)
+    [0] pvno EXPLICIT INTEGER id: 0 (0xa0), len: 3 (0x03)
      0000  02 01 05                                         ...
    pvno INTEGER id: 2 (0x02), len: 1 (0x01)    5 (0x05)
-    msg_type EXPLICIT INTEGER id: 1 (0xa1), len: 3 (0x03)
+    [1] msg_type EXPLICIT INTEGER id: 1 (0xa1), len: 3 (0x03)
      0000  02 01 1e                                         ...
```

I wonder if for something like explicit constructed values like `integer(:pvno, explicit: 0, constructed: true)` - the indentation could increase too, to help logically group them better:

```diff
 SEQUENCE id: 16 (0x30), len: 138 (0x818a)
   pvno EXPLICIT INTEGER id: 0 (0xa0), len: 3 (0x03)
     0000  02 01 05                                         ...
-  pvno INTEGER id: 2 (0x02), len: 1 (0x01)    5 (0x05)
+     pvno INTEGER id: 2 (0x02), len: 1 (0x01)    5 (0x05)
```

For context, this was my test script:

```ruby
require 'rasn1'
require 'base64'

RASN1::Types.define_type('Uint32', from: RASN1::Types::Integer) do |value|
  (value >= 0) && (value < 2 ** 32)
end
RASN1::Types.define_type('Int32', from: RASN1::Types::Integer) do |value|
  (value >= -2 ** 31) && (value < 2 ** 31)
end
RASN1::Types.define_type('KerberosMicroseconds', from: RASN1::Types::Integer)
RASN1::Types.define_type('KerberosTime', from: RASN1::Types::GeneralizedTime)
RASN1::Types.define_type('KerberosFlags', from: RASN1::Types::BitString)
RASN1::Types.define_type('KerberosTicketFlags', from: RASN1::Types::KerberosFlags)

class KerberosString < RASN1::Types::IA5String
  # Important: Using GraphicString's id value of 27, instead of IA5String's ID of 22
  ID = 27

  # Get ASN.1 type
  # @return [String]
  def self.type
    'KerberosString'
  end
end

RASN1::Types.define_type('KerberosString', from: KerberosString)
RASN1::Types.define_type('KerberosRealm', from: RASN1::Types::KerberosString)

class PrincipalName < RASN1::Model
  sequence :PrincipalName,
           content: [
             int32(:name_type, explicit: 0, constructed: true),
             sequence_of(:name_string, RASN1::Types::KerberosString, explicit: 1, constructed: true)
           ]
end

class KrbError < RASN1::Model
  sequence :KrbError,
           class: :application,
           explicit: 30,
           content: [
             integer(:pvno, explicit: 0, constructed: true),
             integer(:msg_type, explicit: 1, constructed: true),
             kerberos_time(:ctime, explicit: 2, constructed: true, optional: true),
             kerberos_microseconds(:cusec, explicit: 3, constructed: true, optional: true),
             kerberos_time(:stime, explicit: 4, constructed: true),
             kerberos_microseconds(:susec, explicit: 5, constructed: true),
             uint32(:error_code, explicit: 6, constructed: true),
             kerberos_realm(:crealm, explicit: 7, constructed: true, optional: true),
             wrapper(model(:cname, PrincipalName), explicit: 8, constructed: true, optional: true),
             kerberos_realm(:realm, explicit: 9, constructed: true),
             wrapper(model(:sname, PrincipalName), explicit: 10, constructed: true),
             kerberos_string(:e_text, explicit: 11, constructed: true, optional: true),
             octet_string(:e_data, explicit: 12, constructed: true, optional: true),
           ]
end

valid_data =
  "\x7e\x81\x8d\x30\x81\x8a\xa0\x03\x02\x01\x05\xa1" \
  "\x03\x02\x01\x1e\xa4\x11\x18\x0f\x32\x30\x31\x34\x31\x32\x31\x34" \
  "\x32\x32\x34\x35\x32\x32\x5a\xa5\x05\x02\x03\x07\x5a\x47\xa6\x03" \
  "\x02\x01\x18\xa9\x0c\x1b\x0a\x44\x45\x4d\x4f\x2e\x4c\x4f\x43\x41" \
  "\x4c\xaa\x1f\x30\x1d\xa0\x03\x02\x01\x01\xa1\x16\x30\x14\x1b\x06" \
  "\x6b\x72\x62\x74\x67\x74\x1b\x0a\x44\x45\x4d\x4f\x2e\x4c\x4f\x43" \
  "\x41\x4c\xac\x30\x04\x2e\x30\x2c\x30\x16\xa1\x03\x02\x01\x0b\xa2" \
  "\x0f\x04\x0d\x30\x0b\x30\x09\xa0\x03\x02\x01\x17\xa1\x02\x04\x00" \
  "\x30\x12\xa1\x03\x02\x01\x13\xa2\x0b\x04\x09\x30\x07\x30\x05\xa0" \
  "\x03\x02\x01\x17".b

RASN1.trace($stderr) do
  KrbError.parse(valid_data)
end
```

**Comment by sdaubert** [comment]
@adfoster-r7 OK for indenting explicit content. I had searched for it for days but i have finally made it work!

**Comment by sdaubert** [comment]
About formatting, change it to appear a bit like ASN.1 syntax:

```
        seqof [ 16 ] SEQUENCE OF (0x30), len: 18 (0x12)
          record [ 16 ] SEQUENCE (0x30), len: 6 (0x06)
            id [ 2 ] INTEGER (0x02), len: 1 (0x01)    15 (0x0f)
            room [ CONTEXT 0 ] IMPLICIT INTEGER OPTIONAL (0x80), len: 1 (0x01)    2 (0x02)
            house [ CONTEXT 1 ] EXPLICIT INTEGER DEFAULT VALUE 0
          record [ 16 ] SEQUENCE (0x30), len: 8 (0x08)
            id [ 2 ] INTEGER (0x02), len: 1 (0x01)    16 (0x10)
            room [ CONTEXT 0 ] IMPLICIT INTEGER OPTIONAL NONE
            house [ CONTEXT 1 ] EXPLICIT INTEGER (0x81), len: 3 (0x03)
              0000  02 01 03                                         ...
              house [ 2 ] INTEGER (0x02), len: 1 (0x01)    3 (0x03)
```

**Comment by adfoster-r7** [comment]
Looks good to me 💯

**Pull request merged**
